#!/bin/bash

var1=A

my_function () {
	local var2=B
	var3=C
	echo "Inside function: var1=$var1, var2=$var2, var3=$var3"
}

echo "Before running function: var1=$var1, var2=$var2, var3=$var3"

my_function

echo "After running function: var1=$var1, var2=$var2, var3=$var3"

exit 0
