#!/bin/bash

echo "You have selected service $1 to be installed"

if grep -i 'ubuntu' /etc/os-release
then
        echo "You're running Ubuntu!"
        sudo apt install -y $1
elif grep -i 'red hat' /etc/os-release
then
        echo "You're running Red Hat!"
        sudo dnf install -y $1
fi

[[ $? == 0 ]] && sudo systemctl enable --now $1
[[ $? == 0 ]] && sudo systemctl status $1 | grep 'active (running)'
[[ $? == 0 ]] && echo "The service $1 was successfully installed and started!" || echo "The script has failed!"
