#!/bin/bash



FREE_DISK_G="$(df -H | grep '/$' | awk '{ print $4 }')"
FREE_DISK="${FREE_DISK_G%G}"
FREE_MEM="$(free -m | grep '^Mem' | awk '{ print $4 }')"

read -p "Enter the lower limit for disk space (in GB): " DISK_LIM
read -p "Enter the lower limit for free memory (in MB): " MEM_LIM

if (( ($FREE_DISK < $DISK_LIM) && ($FREE_MEM < $MEM_LIM) ))
then
	echo "WARNING: low system resources!"
	exit 9
elif (( $FREE_DISK < $DISK_LIM ))
then
	echo "WARNING: low disk space available!"
	exit 8
elif (( $FREE_MEM < $MEM_LIM ))
then
	echo "WARNING: low memory available!"
	exit 7
else
	echo "System resources on normal levels"
fi
exit 0
