#!/bin/bash

PS3='Enter your choice: '
options=("Option 1" "Option 2" "Option 3" "Quit")

select opt in "${options[@]}"
do
	case $opt in
		"Option 1")
			echo "You have selected option 1"
			;;
		"Option 2")
			echo "You have selected option 2"
			;;
		"Option 3")
			echo "You have selected $REPLY which is $opt"
			;;
		"Quit")
			break
			;;
		*)
			echo "Invalid option $REPLY"
			;;
	esac
done

exit 0
