#!/bin/bash

echo "Hello $1, how are you today?"
echo "\$\# gives $#"
echo "\$* gives $*"
echo "\$@ gives $@"
echo "\$0 gives $0"

# Trying to show every single argument on a separate line
echo "Showing the interpretation of \$*"
for i in "$*"
do
	echo $i
done

echo "Showing the interpretation of \$@"
for i in "$@"
do
	echo $i
done
