#!/bin/bash

COUNTER=$1
COUNTER=$(( COUNTER * 60 ))

minusone () {
	COUNTER=$(( COUNTER - 1 ))
	sleep 1
}

while [ $COUNTER -gt 0 ]
do
	echo "$COUNTER seconds left"
	minusone
done

[ $COUNTER = 0 ] && echo "Time is up!" && minusone
[ $COUNTER = "-1" ] && echo "You are now one second late" && minusone

while true
do
	echo "You are now ${COUNTER#-} seconds late"
	minusone
done
